CREATE DATABASE IF NOT EXISTS dota2_db;
USE dota2_db;

CREATE TABLE user_inf(
	ID INT(32) NOT NULL AUTO_INCREMENT,
	account VARCHAR(50),
	password VARCHAR(50),
	dota2_acc_id BIGINT DEFAULT 0,
	NAME VARCHAR(50) DEFAULT 'user',
	IMG VARCHAR(50) DEFAULT 'default',
	phone VARCHAR(20) DEFAULT NULL,
	qq_num VARCHAR(20) DEFAULT NULL,
	email VARCHAR(50) DEFAULT null,
	wxid VARCHAR(64) DEFAULT null,
	isSys INT(1) DEFAULT 0,
	steam_code VARCHAR(64) DEFAULT NULL,
	steam_name VARCHAR(64) DEFAULT NULL,
	win INT(32) DEFAULT 0,
	loby7 INT(32) DEFAULT 0,
	loby7win INT(32) DEFAULT 0,
	PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE match_inf(
	ID BIGINT(32) NOT NULL AUTO_INCREMENT,
	mat_id BIGINT NOT NULL,
	seq BIGINT NOT NULL,
	start BIGINT NOT NULL,
	duration INT(8) NOT NULL,
	radiant_win INT(1) NOT NULL,
	cluster INT(5) DEFAULT NULL,
	first_blood_time INT(32) DEFAULT NULL,
	lobby_type INT(2) NOT NULL,
	leagueid INT(16) DEFAULT 0,
	game_mode INT(3) NOT NULL,
	radiant_score INT(4) DEFAULT 0,
	dire_score INT(4) DEFAULT 0,
	PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE user_mat_inf(
	ID BIGINT(32) NOT NULL AUTO_INCREMENT,
	acc_id BIGINT NOT null,
	mat_id BIGINT NOT null,
	solt INT(1) NOT NULL,
	hero_id INT(3) NOT NULL,
	item0 INT(32) DEFAULT 0,
	item1 INT(32) DEFAULT 0,
	item2 INT(32) DEFAULT 0,
	item3 INT(32) DEFAULT 0,
	item4 INT(32) DEFAULT 0,
	item5 INT(32) DEFAULT 0,
	bac0 INT(32) DEFAULT 0,
	bac1 INT(32) DEFAULT 0,
	bac2 INT(32) DEFAULT 0,
	bac3 INT(32) DEFAULT 0,
	kill_num INT(4) DEFAULT 0,
	deaths INT(4) DEFAULT 0,
	assists INT(4) DEFAULT 0,
	leaver_status INT(2) DEFAULT 0,
	last_hit INT(4) DEFAULT 0,
	denis INT(4) DEFAULT 0,
	gpm INT(4) DEFAULT 0,
	xpm INT(4) DEFAULT 0,
	level INT(2) DEFAULT 1,
	hero_damage INT(8) DEFAULT 0,
	tower_damage INT(8) DEFAULT 0,
	hero_healing INT(8) DEFAULT 0,
	gold_spent INT(8) DEFAULT 0,
	ability_code1 INT(8) DEFAULT 0,
	ability_time1 INT(8) DEFAULT 0,
	ability_level1 INT(2) DEFAULT 0,
	ability_code2 INT(8) DEFAULT 0,
	ability_time2 INT(8) DEFAULT 0,
	ability_level2 INT(2) DEFAULT 0,
	ability_code3 INT(8) DEFAULT 0,
	ability_time3 INT(8) DEFAULT 0,
	ability_level3 INT(2) DEFAULT 0,
	ability_code4 INT(8) DEFAULT 0,
	ability_time4 INT(8) DEFAULT 0,
	ability_level4 INT(2) DEFAULT 0,
	ability_code5 INT(8) DEFAULT 0,
	ability_time5 INT(8) DEFAULT 0,
	ability_level5 INT(2) DEFAULT 0,
	ability_code6 INT(8) DEFAULT 0,
	ability_time6 INT(8) DEFAULT 0,
	ability_level6 INT(2) DEFAULT 0,
	ability_code7 INT(8) DEFAULT 0,
	ability_time7 INT(8) DEFAULT 0,
	ability_level7 INT(2) DEFAULT 0,
	ability_code8 INT(8) DEFAULT 0,
	ability_time8 INT(8) DEFAULT 0,
	ability_level8 INT(2) DEFAULT 0,
	ability_code9 INT(8) DEFAULT 0,
	ability_time9 INT(8) DEFAULT 0,
	ability_level9 INT(2) DEFAULT 0,
	ability_code10 INT(8) DEFAULT 0,
	ability_time10 INT(8) DEFAULT 0,
	ability_level10 INT(2) DEFAULT 0,
	ability_code11 INT(8) DEFAULT 0,
	ability_time11 INT(8) DEFAULT 0,
	ability_level11 INT(2) DEFAULT 0,
	ability_code12 INT(8) DEFAULT 0,
	ability_time12 INT(8) DEFAULT 0,
	ability_level12 INT(2) DEFAULT 0,
	ability_code13 INT(8) DEFAULT 0,
	ability_time13 INT(8) DEFAULT 0,
	ability_level13 INT(2) DEFAULT 0,
	ability_code14 INT(8) DEFAULT 0,
	ability_time14 INT(8) DEFAULT 0,
	ability_level14 INT(2) DEFAULT 0,
	ability_code15 INT(8) DEFAULT 0,
	ability_time15 INT(8) DEFAULT 0,
	ability_level15 INT(2) DEFAULT 0,
	ability_code16 INT(8) DEFAULT 0,
	ability_time16 INT(8) DEFAULT 0,
	ability_level16 INT(2) DEFAULT 0,
	ability_code17 INT(8) DEFAULT 0,
	ability_time17 INT(8) DEFAULT 0,
	ability_level17 INT(2) DEFAULT 0,
	ability_code18 INT(8) DEFAULT 0,
	ability_time18 INT(8) DEFAULT 0,
	ability_level18 INT(2) DEFAULT 0,
	ability_code19 INT(8) DEFAULT 0,
	ability_time19 INT(8) DEFAULT 0,
	ability_level19 INT(2) DEFAULT 0,
	ability_code20 INT(8) DEFAULT 0,
	ability_time20 INT(8) DEFAULT 0,
	ability_level20 INT(2) DEFAULT 0,
	ability_code21 INT(8) DEFAULT 0,
	ability_time21 INT(8) DEFAULT 0,
	ability_level21 INT(2) DEFAULT 0,
	ability_code22 INT(8) DEFAULT 0,
	ability_time22 INT(8) DEFAULT 0,
	ability_level22 INT(2) DEFAULT 0,
	ability_code23 INT(8) DEFAULT 0,
	ability_time23 INT(8) DEFAULT 0,
	ability_level23 INT(2) DEFAULT 0,
	ability_code24 INT(8) DEFAULT 0,
	ability_time24 INT(8) DEFAULT 0,
	ability_level24 INT(2) DEFAULT 0,
	ability_code25 INT(8) DEFAULT 0,
	ability_time25 INT(8) DEFAULT 0,
	ability_level25 INT(2) DEFAULT 0,
	INDEX(acc_id),
	INDEX(mat_id),
	PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;


